server:
  port: 8084
  #  connection-timeout: 1800000新版本不适合
  servlet:
    session:
      timeout: 30m #30分钟，测试的话时间不能太短，否则不准，不写单位默认毫秒pring：
    name: usertest #springboot的名称，在cloud的集群众表示当前应用

spring:
  application:
    name: usertest #springboot的名称，在cloud的集群众表示当前应用

user:
  key1: uservalue